version: '3.8'

services:
  app:
    container_name: it-roadmap-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8900:8889"
    environment:
      - DB_HOST=database
      - DB_DATABASE=it_roadmap
      - DB_USERNAME=user
      - DB_PASSWORD=123456
    volumes:
      - appdata:/var/www/html/storage/app
      - logdata:/var/www/html/storage/logs

  database:
    container_name: it-roadmap-db
    image: mysql:5.7
    ports:
      - "8910:3306"
    restart: always
    environment:
      - MYSQL_DATABASE=it_roadmap
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
  appdata:
  logdata: